### Listar todos os livros
GET http://localhost:3003/livros

### Buscar um livro por ID
GET http://localhost:3003/livros/1

### Buscar livros por Autor (Ex: Busca parcial/ILIKE igual a Anna explicou!)
GET http://localhost:3003/livros/autor/Machado

### Buscar livros por Título
GET http://localhost:3003/livros/titulo/Codigo

### Buscar um livro por ISBN
GET http://localhost:3003/livros/isbn/9788575222485

### Criar um novo livro
POST http://localhost:3003/livros
Content-Type: application/json

{
  "titulo": "Código Limpo",
  "isbn": "9788575222485"
}

### Atualizar livro (Apenas título e/ou isbn são aceitos no seu repository)
PUT http://localhost:3003/livros/1
Content-Type: application/json

{
  "titulo": "Código Limpo - Edição Revisada",
  "isbn": "9788575222485"
}

### Deletar um livro
DELETE http://localhost:3003/livros/1